// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htnidjlzxnjdfagvuuog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0bmlkamx6eG5qZGZhZ3Z1dW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODg1MjAsImV4cCI6MjA2MDM2NDUyMH0.mIg18HjVbyiMahNp5iI7YevCYfgkCeNY6UOI7jvRomY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);